//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbDarwin.Service.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DbDarwin.Service.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  
        ///  RC.CONSTRAINT_SCHEMA,
        ///  RC.CONSTRAINT_NAME,
        ///  RC.UNIQUE_CONSTRAINT_NAME,
        ///  RC.MATCH_OPTION,
        ///  RC.UPDATE_RULE,
        ///  RC.DELETE_RULE,
        ///
        ///  KCU1.Table_Name,
        ///  KCU1.COLUMN_NAME,
        ///  KCU1.ORDINAL_POSITION,
        ///
        ///  KCU2.TABLE_SCHEMA as Ref_TABLE_SCHEMA,
        ///  KCU2.TABLE_NAME as Ref_TABLE_NAME,
        ///  KCU2.COLUMN_NAME as Ref_COLUMN_NAME,
        ///  KCU2.ORDINAL_POSITION as Ref_ORDINAL_POSITION
        ///
        ///FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS AS RC 
        ///
        ///INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS KCU1 
        ///    ON KC [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string REFERENTIAL_CONSTRAINTS {
            get {
                return ResourceManager.GetString("REFERENTIAL_CONSTRAINTS", resourceCulture);
            }
        }
    }
}
