SELECT  
  RC.CONSTRAINT_SCHEMA,
  RC.CONSTRAINT_NAME,
  RC.UNIQUE_CONSTRAINT_NAME,
  RC.MATCH_OPTION,
  RC.UPDATE_RULE,
  RC.DELETE_RULE,

  KCU1.TABLE_SCHEMA,
  KCU1.TABLE_NAME,
  KCU1.COLUMN_NAME,
  KCU1.ORDINAL_POSITION,

  KCU2.TABLE_SCHEMA as Ref_TABLE_SCHEMA,
  KCU2.TABLE_NAME as Ref_TABLE_NAME,
  KCU2.COLUMN_NAME as Ref_COLUMN_NAME,
  KCU2.ORDINAL_POSITION as Ref_ORDINAL_POSITION

FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS AS RC 

INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS KCU1 
    ON KCU1.CONSTRAINT_CATALOG = RC.CONSTRAINT_CATALOG  
    AND KCU1.CONSTRAINT_SCHEMA = RC.CONSTRAINT_SCHEMA 
    AND KCU1.CONSTRAINT_NAME = RC.CONSTRAINT_NAME 

INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS KCU2 
    ON KCU2.CONSTRAINT_CATALOG = RC.UNIQUE_CONSTRAINT_CATALOG  
    AND KCU2.CONSTRAINT_SCHEMA = RC.UNIQUE_CONSTRAINT_SCHEMA 
    AND KCU2.CONSTRAINT_NAME = RC.UNIQUE_CONSTRAINT_NAME 
    AND KCU2.ORDINAL_POSITION = KCU1.ORDINAL_POSITION 